# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HxTable',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='\u7528\u6237ID')),
                ('uuid', models.TextField(blank=True, verbose_name='\u73af\u4fe1\u7528\u6237ID')),
                ('created', models.IntegerField(blank=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.IntegerField(blank=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('username', models.TextField(blank=True, verbose_name='\u7528\u6237\u540d')),
                ('nickname', models.TextField(blank=True, verbose_name='\u6635\u79f0')),
                ('password', models.TextField(blank=True, verbose_name='\u5bc6\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTable',
            fields=[
                ('token', models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='Token')),
                ('id', models.IntegerField(blank=True, verbose_name='\u7528\u6237ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7528\u6237ID')),
                ('nickname', models.TextField(blank=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.TextField(blank=True, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('head', models.TextField(blank=True, verbose_name='\u7528\u6237\u5934\u50cf')),
            ],
        ),
    ]
